[build]
builder = "nixpacks"

[build.nixpacks]
phpVersion = "8.4"

[deploy]
startCommand = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT}"
preDeployCommand = "php artisan optimize:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache"
